import Button from "@/app/components/Button";
import CustomLink from "@/app/components/CustomLink";

export default function Settings() {
  return (
    <div>
      <h1 className="text-2xl">Settings</h1>
      <Button path="/analytics">Go to Analytics</Button> <br />
      <br />
      <Button path="/dashboard">Go to Dashboard</Button> <br /> <br />
      <Button path="#red"> Go the Red Section</Button>
      <section id="green" className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section id="red" className="border-2 p-4 m-4 rounded text-red-500">
      <CustomLink path={'#green'}>  Red Lorem</CustomLink>
      </section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
      <section className="border-2 p-4 m-4 rounded text-white">lorem</section>
    </div>
  );
}
